
karyotype = c:/Users/hoang/Documents/project_test/major_industry_circos_draft1/custom_circos_v4_eng/karyotype.txt
chromosomes_units = 1
chromosomes_display_default = yes

<image>
dir = c:/Users/hoang/Documents/project_test/major_industry_circos_draft1/custom_circos_v4_eng
file = v4_eng_circos.png
png = yes
svg = no
radius = 1500p
background = white
angle_offset = -90
auto_alpha_colors = yes
auto_alpha_steps = 5
</image>

<ideogram>
  <spacing>
    default = 0.005r
    <pairwise major_0 career_0>
      spacing = 15r
    </pairwise>
    <pairwise career_10 major_0>
      spacing = 15r
    </pairwise>
  </spacing>
  radius = 0.85r
  thickness = 40p
  fill = yes
  stroke_color = white
  stroke_thickness = 4p
  
  show_label = yes
  label_font = default
  label_radius = 1.05r
  label_size = 40
  label_parallel = yes
</ideogram>

show_ticks = no
show_tick_labels = no

<links>
<link>
file = c:/Users/hoang/Documents/project_test/major_industry_circos_draft1/custom_circos_v4_eng/links.txt
radius = 0.84r
bezier_radius = 0.5r
thickness = 2
ribbon = yes
</link>
</links>

<<include c:/Users/hoang/Documents/project_test/major_industry_circos_draft1/custom_circos_v4_eng/colors.conf>>
<<include C:/Users/hoang/Downloads/circos-0.69-10/circos-0.69-10/etc/colors_fonts_patterns.conf>>
<<include C:/Users/hoang/Downloads/circos-0.69-10/circos-0.69-10/etc/housekeeping.conf>>
