karyotype = karyotype.txt
chromosomes_units = 1
chromosomes_display_default = yes

<image>
dir = .
file = arts_theology_native.png
png = yes
svg = yes
radius = 1800p
background = white
angle_offset = 114
auto_alpha_colors = yes
auto_alpha_steps = 5
</image>

<ideogram>
  <spacing>
    default = 0.010r
    <pairwise career_Unclassified career_Business_Finance>
      spacing = 2r
    </pairwise>
    <pairwise career_Business_Finance career_Healthcare_Science>
      spacing = 2r
    </pairwise>
    <pairwise career_Healthcare_Science career_Technology_Engineering>
      spacing = 2r
    </pairwise>
    <pairwise career_Technology_Engineering career_Education_Service>
      spacing = 2r
    </pairwise>
    <pairwise career_Education_Service career_Arts_Media_Legal>
      spacing = 2r
    </pairwise>
    <pairwise major_Catholic_Studies major_Music_Business>
      spacing = 2r
    </pairwise>
    <pairwise major_Music_Business major_Music>
      spacing = 2r
    </pairwise>
    <pairwise major_Music major_Theology>
      spacing = 2r
    </pairwise>
    <pairwise major_Theology major_Art_History>
      spacing = 2r
    </pairwise>
    <pairwise major_Art_History major_Music_Performance>
      spacing = 2r
    </pairwise>
    <pairwise major_Music_Performance major_English>
      spacing = 4r
    </pairwise>
    <pairwise major_English major_English_Professional_Writing>
      spacing = 2r
    </pairwise>
    <pairwise major_English_Professional_Writing major_Spanish_Cultural_Literary_St>
      spacing = 4r
    </pairwise>
    <pairwise major_Spanish_Cultural_Literary_St major_French>
      spacing = 2r
    </pairwise>
    <pairwise major_French major_Spanish_Linguistics_Lang_St>
      spacing = 2r
    </pairwise>
    <pairwise major_Spanish_Linguistics_Lang_St major_German>
      spacing = 2r
    </pairwise>
    <pairwise career_Arts_Media_Legal major_Catholic_Studies>
      spacing = 22r
    </pairwise>
    <pairwise major_German career_Unclassified>
      spacing = 22r
    </pairwise>
  </spacing>
radius = 0.87r
  thickness = 48p
  fill = yes
  stroke_color = white
  stroke_thickness = 5p
  show_label = no
  label_font = default
  label_radius = 1.10r
  label_size = 24
  label_parallel = yes
</ideogram>

show_ticks = no
show_tick_labels = no

<links>
<link>
file = links.txt
radius = 0.83r
bezier_radius = 0.18r
thickness = 2
ribbon = yes
flat = yes
stroke_thickness = 0
stroke_color = dgrey
</link>
</links>

<plots>
<plot>
type = text
color = black
file = labels.txt
r0 = 1.04r
r1 = 1.30r
label_size = 18p
label_font = default
show_links = no
padding = 0r
rpadding = 0r
label_snuggle = yes
snuggle_tolerance = 0.6r
max_snuggle_distance = 2r
</plot>
</plots>

<<include colors.conf>>
<<include __CIRCOS_ROOT__/etc/colors_fonts_patterns.conf>>
<<include __CIRCOS_ROOT__/etc/housekeeping.conf>>
