karyotype = karyotype.txt
chromosomes_units = 1
chromosomes_display_default = yes

<image>
dir = .
file = portable_major_industry.png
png = yes
svg = no
radius = 1500p
background = white
angle_offset = -90
auto_alpha_colors = yes
auto_alpha_steps = 5
</image>

<ideogram>
  <spacing>
    default = 0.005r
    <pairwise major_7 industry_0>
      spacing = 15r
    </pairwise>
    <pairwise industry_10 major_0>
      spacing = 15r
    </pairwise>
  </spacing>
  radius = 0.85r
  thickness = 40p
  fill = yes
  stroke_color = white
  stroke_thickness = 4p
  show_label = yes
  label_font = default
  label_radius = 1.10r
  label_size = 38
  label_parallel = yes
</ideogram>

show_ticks = no
show_tick_labels = no

<links>
<link>
file = links.txt
radius = 0.84r
bezier_radius = 0.5r
thickness = 1
ribbon = yes
flat = yes
</link>
</links>

<<include colors.conf>>
<<include C:/Users/hoang/Downloads/circos-0.69-10/circos-0.69-10/etc/colors_fonts_patterns.conf>>
<<include C:/Users/hoang/Downloads/circos-0.69-10/circos-0.69-10/etc/housekeeping.conf>>
