# Image output configuration

dir   = .
file  = major_industry_circos.png
png   = yes
svg   = yes

# Image dimensions
radius         = 1500p
background     = white
angle_offset   = -90

# For high-quality output
auto_alpha_colors = yes
auto_alpha_steps  = 5
